### ISSUE TITLE
FileNotFoundError: [WinError 2]

### ISSUE THREAD

**Issue by Koshkodav** [offici5l/MiUnlockTool#68]
Good localtime!
I have the problem.
Phone - Poco M5
Current OS - MIUI Global 14.0.9 (TLUMIXM)
PC OS - Win10(x64) 21H2
Python - 3.12.2
Cable for connect - original
USB port version - 2.0

From console -
```
AccountInfo:
id: ** here is correct id **
region: RU
Ensure you're in Bootloader mode (fastboot mode)

Traceback (most recent call last):
  File "c:\MiUnlockTool-1.5.7\MiUnlockTool.py", line 296, in <module>
    unlocked = CheckB(cmd, "unlocked", "getvar", "unlocked")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\MiUnlockTool-1.5.7\MiUnlockTool.py", line 263, in CheckB
    process = subprocess.Popen([cmd] + list(fastboot_args), stdout=subprocess.PIPE, stderr=subprocess.PIPE, bufsize=1, universal_newlines=True)              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] Не удается найти указанный файл
```
Can you point out my mistake?

**Comment by offici5l** [comment]
Please use version 1.6.0.
