### ISSUE TITLE
 Unlock phone with hyperos

### ISSUE THREAD

**Issue by pjakubina** [offici5l/MiUnlockTool#9]
When I try to unlock my redmi k60 with hyperos I get this error. How do I fix it?
```
Traceback (most recent call last):
  File "/root/xiaomi/MiBypassTool.py", line 105, in <module>
    headers = {"Cookie": re.search(r"Cookie=\[(.*)\]", AES.new(b'20nr1aobv2xi8ax4', AES.MODE_CBC, b'0102030405060708').decrypt(base64.b64decode(headers)).rstrip(b'\0').decode('utf-8')).group(1).strip(), "Content-Type": "application/x-www-form-urlencoded"}
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb6 in position 2: invalid start byte
```

**Comment by pjakubina** [comment]
Sorry my mistake, how do I do the downgrade settings app?

**Comment by pjakubina** [comment]
Thank you, it helped but does not support my system which I no longer like.
```

version: V816.0.6.0.UMNCNXM

change version to: V14.0.6.0.UMNCNXM

code: 401

description: 参数过期，请重试

descCN: 参数过期，请重试

descEN: Param expired. Please try again.
```

**Comment by pjakubina** [comment]
New error
```

version: V816.0.6.0.UMNCNXM

code: 30001

description: 绑定失败，请前往小米社区内测中心申请授权后重试

descCN: 绑定失败，请前往小米社区内测中心申请授权后重试

descEN: Couldn't add. Please go to Mi Community to apply for authorization and try again.
```
I would love to enter mi community but unfortunately on this phone this app is not in English and the one that is is not understandable to me

**Comment by pjakubina** [comment]
This work but
log from terminal
```
Now bind your account in Mi Unlock status ...


version: V816.0.6.0.UMNCNXM

change version to: V14.0.6.0.UMNCNXM

Linked successfully


Press Enter to exit ...
```
ss from phone
![obraz](https://github.com/offici5l/MiUnlockTool/assets/112482062/48793230-6bcb-481d-93de-6dbd2377af8b)

**Comment by pjakubina** [comment]
Ok, when i use MiUnlockTool in terminal have

```
Traceback (most recent call last):
  File "/home/pekto/MiUnlockTool.py", line 186, in <module>
    data = json.loads(requests.get("https://account.xiaomi.com/pass/serviceLogin?sid=unlockApi&_json=true&passive=true&hidden=true", headers=headers, cookies={'passToken': p['passToken'], 'userId': str(p['userId']), 'deviceId': parse_qs(urlparse(p['location']).query)['d'][0]}).text.replace("&&&START&&&", ""))
                                                                                                                                                                            ~^^^^^^^^^^^^^
KeyError: 'passToken'
```

**Comment by pjakubina** [comment]
Result this code
```

{'notificationUrl': 'https://account.xiaomi.com/identity/authStart?sid=passport&context=nBiwm79iFSN1LbGsOKbCWuCUEQwoHO0BB9uVHucP8O4ZTdNIOY472Arg81cbp6RmllImHEte9iIKO4LOY8Z6KAbHgwITyb5rBitQUYw6rv9R1ZffOckYxtSG3KgN0s0rotqp7iMpbziBQO8w5EtjIrhFOfhGitn7utVnwM6JiAGHZu2NH6i2RPb12KFV9JlxBDZYOUZya9lHzt4Ey3mt2V1_CNtU9Uny4eTAORJmsBJrB2BpcQtoN72sXhhxUD2gNPH1q-sPW-E0iWmS3Ky_ksFlUY-YI-au2cDlHVbtKJx9nbRFyiMfRL-lvTEHyCf-dsQVAGMnl8Q4ypTsRA79W6CzHc7S-1c0cGVl79smKpA1XmqyvVXjZt5nCy5yngPuIbLgyUGHy83pkm_aUDt5_Z7z0_eUB2degsoIkMqqc2UllCk5o4VU9BiP4FiqLfsqeQo59ejSOU1XE1h8557nA8ExgJIgIJ6u-bLb-lMHDOKoRij5bEZbfvclV9JS9NQz8UEnP5EDtdV6mR29IlvGvf1Wyr6ndqG-f7YjfiNiftpcjeE6maH02_pGfNhuEUzZeaZFHyzZ57UnoDWCHjty79DBzPUFgR8vSI1lV22pczeHrBz3VR8r-KmwRrT0Ja2NfWBWOaGQty53U6hpgMy61FctvHmlbM2RUwrTwszx-qmmaBo8m796FX_ef-2e7FiYEm607C1JkBoFL0GnddFXUTN31tjyiwR98wm7CGxutrjto97G-F2nD6g9ucTJFP7HUwi_UFKG78_Pg0IynwA82w&_locale=pl_PL', 'result': 'ok', 'code': 0, 'captchaUrl': None, 'description': '成功', 'location': '', 'securityStatus': 16, 'pwd': 0, 'child': 0, 'desc': '成功'}
Traceback (most recent call last):
  File "/home/pekto/MiUnlockTool.py", line 187, in <module>
    data = json.loads(requests.get("https://account.xiaomi.com/pass/serviceLogin?sid=unlockApi&_json=true&passive=true&hidden=true", headers=headers, cookies={'passToken': p['passToken'], 'userId': str(p['userId']), 'deviceId': parse_qs(urlparse(p['location']).query)['d'][0]}).text.replace("&&&START&&&", ""))
                                                                                                                                                                            ~^^^^^^^^^^^^^
KeyError: 'passToken'

```

**Comment by pjakubina** [comment]
Thanks a lot for everything, it helped
